insert INTO subcontent (content,sub_type) values ("Literature",0),
("U.S. History",0),
("World History",0),
("Math Level 1",0),
("Math Level 2",0),
("Biology Ecology",0),
("Chemistry",0),
("Physics",0),
("Other Languages",0),
("Biochemistry Cell and Molecular Biology",1),
("Literature in English",1),
("Biology",1),
("Mathematics",1),
("Chemistry",1),
("Physics",1),
("Computer Science",1),
("Psychology",1);